//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despacho
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public int idTda { get; set; }
        public int idCliente { get; set; }
        public int idProducto { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Tipo_de_accion Tipo_de_accion { get; set; }
    }
}
