//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos_Por_Rol
    {
        public int id { get; set; }
        public int idRol { get; set; }
        public int idPermisos { get; set; }
    
        public virtual Permiso Permiso { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
