// <auto-generated />
namespace Proy_Fin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserNombre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserNombre));
        
        string IMigrationMetadata.Id
        {
            get { return "202003301805451_UserNombre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
